### PR TITLE
Restructuring code base for `Sequence` and attached classes

### PR DESCRIPTION
**Pull request by psomhorst**
This is a major restructuring of `Sequence` and attached classes.
See [this branch](https://github.com/EIT-ALIVE/eitprocessing/tree/notes/refactor_proposal) contains the html with the updated proposal) for the updated schema for the proposed `Sequence` class structured.

diagram

----------

Changes that have been made include:
- Sequence was mainly a container of EIT data. This responsibility has
been moved to EITData.
- Subclasses of EITData (previously subclasses of Sequence) for
different vendors are in separate modules.
- The responsibility of Frameset has moved to EITDataVariant.
- Visualisation tools have been moved to a separate module `plotting`.
- The Vendor class has been moved to it's own module.
- `merge()` methods are now called `concatenate()`.

This is the start of the road for this refactoring. Up to this point,
there is very limited functionality and testing.

What works*:
- DraegerEITData.from_path() works.
- TimpelEITData.from_path() works.
- EITData.from_path(..., vendor="draeger") works.
- DraegerEITData.concatenate() works. This includes
VariantCollection.concatenate() and EITVariant.concatenate().
- DraegerEITData.check_equivalence() is working.
- When DraegerEITData is loaded, you can also have a ContinuousDataCollection returned containing the continuous waveforms contained in the data file (sparse data is yet to be implemented).

*: Untested!

Interface:
```python
a = DraegerEITData.from_path("test_data/a.bin")
b, continuous, sparse = DraegerEITData.from_path("test_data/b.bin", return_non_eit_data=True)
c = a + b
c.variants['raw'].pixel_impedance  # pixel impedance
b['flow'].variants['raw'].values  # flow data from medibus protocol
```

### CODE REVIEW

**Comment by psomhorst** [comment]
## Slicing

It is useful if a Sequence object and attached objects can be sliced in two ways: 
- by time
- by indices

### When time axes don't match

In the refactored design, a Sequence can contain data with different time axes, e.g. EITData from a Sentec device (sample frequency of 50.2 Hz) and ContinuousData from a pressure sensor (sample frequency of 75 Hz). Slicing by index is then not possible, because indices don't point towards the same time points.

```python
sequence = Sequence(
    eit_data=EITData(..., framerate=50.2), 
    continuous_data={'pressure': ContinuousData(..., framerate=75)},
    synchronisation_method=...
)
sliced_sequence = sequence[100:200]  # => Exception: no shared time axis

```

For other cases, a solution could be something like this:
```python
eit_indices = slice(100, 200)
slice_time = eit_data.time[eit_indices]
sliced_sequence = sequence.select_by_time(slice_time)
```

or, in a single statement:

```python
sliced_sequence = sequence.select_by_time(sequence.eit_data.time[100:200])
```

Selection by time can be done on all attached objects individually. This would result in all objects being sliced to start on/after `eit_data.time[100]` and end on/before `eit_data.time[199]`. 

This requires that `select_by_time()` can accept a slice (to allow 'normal' time slicing) and an array/list of time points. If an array/list with time points is passed, only the first and last time point are used, and the rest is ignored.

### When time axes do match

When time axes do match 100% (e.g. `np.array_equal(eit_data.time, continuous_data['pressure'].time)`), index slicing a Sequence is possible. This requires perfect synchronisation and resampling, or all data coming from a single source.

```python
eit_data, waveforms_from_eit_data = DraegerEITData(..., return_waveforms=True)
sequence = Sequence(eit_data=eit_data, continuous_data=waveforms_from_eit_data)
sliced_sequence = sequence[100:200]  # allowed
```

**Comment by psomhorst** [comment]
## TODOs

### Available
- [ ] Write tests for EITData loading
- [ ] Write tests for EITData concatenation
- [ ] Refactor EITData slicing by index and time

### Blocked
- [ ] Write tests for EITData slicing by index and time

**Comment by psomhorst** [comment]
@DaniBodor I've made a start with refactoring Sequence and attached objects. 

I have created a comment at the top with changes compare to the current main. I think we should maintain this somewhat so we know what work has been done.

I will create some issues of tasks that can be done, and some that are blocked by others. 
I think we can tackle these issues in parallel. I will assign issues to myself when I'll be working on them. 

Can you read my proposal for slicing and comment on it? I think it's quite straightforward, but I want to see whether I'm missing anything. Also, if you have any suggestions of how to check common time axes quickly, that would be helpful.

**Comment by psomhorst** [comment]
@wbaccinelli I have made a start with refactoring Sequence and attached classes. I think it's a good idea to take this PR as a basis for loading Sentec data. There are some small changes in how EITData works compared to how Sequence used to work. The class `SentecEITData` inherits from `EITData`. It should re-implement (use @override) the classmethod `from_path()` similarly to `DreagerEITData` and `TimpelEITData`. It should then implement a classmethod `_from_path()` that handles the loading of a single file. 

Because this is early work on the refactoring, documentation and tests are limited. 
I hope this is clear from the examples that are already there. If not, please let me know and I'll add docs/comments where necessary.

**Comment by DaniBodor** [comment]
> ### When time axes don't match
> 
> In the refactored design, a Sequence can contain data with different time axes, e.g. EITData from a Sentec device (sample frequency of 50.2 Hz) and ContinuousData from a pressure sensor (sample frequency of 75 Hz). Slicing by index is not possible, because indices don't point to the same time points in all attached objects.
> 
> ```python
> sequence = Sequence(
>     eit_data=EITData(..., framerate=50.2), 
>     continuous_data={'pressure': ContinuousData(..., framerate=75)},
>     synchronisation_method=...
> )
> sliced_sequence = sequence[100:200]  # => Exception: no shared time axis
> ```

To me the most natural way of slicing any object is by index and it's a bit annoying if something like `sliced_sequence = sequence[100:200]` does not work. I also think it's confusing if it only doesn't work in specific circumstances, no matter how well we document that.
Given that our data is primarily EIT data and anything else is "attached" to that or secondary data, I would argue that we can index-slice based purely on EIT data and send a warning if time axes don't match. I think in the vast majority of cases, this will be what the user expects to happen if they just give an index. We could add an optional argument to our slicing function, to state which object to base the slicing on for cases where a user does want to slice based on index of another data source.
If we do this, we would still need to find a solution for how to match two data sources with different time axes, which is still a bit tricky. There are two possible solutions that I think would make sense (see below) and, again, we could use an argument to allow a user to choose between "unequal total length" or "incomplete first/last slice" (we need better names):
image


What do you think?

**Comment by psomhorst** [comment]
> ...
> Given that our data is primarily EIT data and anything else is "attached" to that or secondary data, I would argue that we can index-slice based purely on EIT data and send a warning if time axes don't match. 
> ...
> 
> What do you think?

I agree. 

I would suggest we do the following:
- `Sequence` objects get an attribute `primary_slicing_target` (better name suggestions are more than welcome) that refers to an `EITData` or `ContinuousData` object.
- `sequence.primary_slicing_target` will be set to `sequence.eit_data` by default if it is available at initialisation.
- `sequence.primary_slicing_target` will be set to the first `continuous_data` that was added otherwise.
- `sequence.primary_slicing_target` can be changed by the end user.
- When merging sequences, the primary slicing target is taken from the first sequence mentioned in the merge method (e.g. with c = a + b, `c.primary_slicing_target` will equal (the copy of) `a.primary_slicing_target`).
- When slicing, the time axis of the primary slicing target is used to get the start and end times. Datasets that have non-matching time axes are sliced based on the start and end time.

I think this makes the system intuitive by default, but adaptive if someone chooses to a) not load EIT data or b) focus on working with other continuous data instead.

**Comment by psomhorst** [comment]
> There are two possible solutions that I think would make sense (see below) and, again, we could use an argument to allow a user to choose between "unequal total length" or "incomplete first/last slice" (we'd need better names):
> 
> image

I was thinking the same. In the second case, the blue squares that you cut in half would just disappear entirely: 

284188981-bfd2232d-c2d0-4a96-b5aa-2ec86ccebf15

It's hard for me to think about what the default behaviour should be from a practical standpoint. I think it makes most sense to use the second case. This would result in the correct behaviour when comparing slicing by indices and by time:

```python
t1 = sequence.eit_data.time[100]
t2 = sequence.eit_data.time[200]

shorter_sequence = sequence[100:200]

assert shorter_sequence == sequence.select_by_time(t1, t2)
assert sequence.continuous_data["pressure"].select_by_time(t1, t2) == sequence[100:200].continuous_data["pressure"]
```

**Comment by DaniBodor** [comment]
> In the second case, the blue squares that you cut in half would just disappear entirely:

I think what you're saying is a third option. 
What I meant is that by index there is the same number of blue timepoints between my suggestions, but that the length/interval of the first and last timepoints are different than for all the other timepoints. So they would indeed be "cut in half".

**Comment by psomhorst** [comment]
24-11-2023: 
We discussed the problem above and agree we should use the **unequal total length**. This should be documented well.

**Comment by psomhorst** [comment]
As per our meeting on 24-11-2023 I have locked pushing to this branch. To merge changes to this branch, you can create a PR.

**Comment by psomhorst** [comment]
@DaniBodor With most of the work for this PR done, are you OK with me unprotecting this branch, so we can push directly to it (instead of having to create PRs for every change)?

**Comment by DaniBodor** [comment]
> @DaniBodor With most of the work for this PR done, are you OK with me unprotecting this branch, so we can push directly to it (instead of having to create PRs for every change)?

I was actually thinking to the contrary, to merge this into main soon and start creating new branches off of there (but still protecting it).

**Comment by psomhorst** [comment]
> [...], to merge this into main soon and start creating new branches off of there (but still protecting it)

Sounds like a great idea! What needs tackling ahead of that merge?

**Comment by DaniBodor** [comment]
> > [...], to merge this into main soon and start creating new branches off of there (but still protecting it)
> 
> Sounds like a great idea! What needs tackling ahead of that merge?

I don't think anything. I mean, I'm sure the checks won't pass yet, as we haven't fixed all the tests yet, and there are still some linting issues, etc to be taken care of. But that can all be done off of main rather than this.
In my mind, we just kept main alive initially, in case this restructuring would have turned out to not be a good idea. But by now, we are so deeply invested and main is so far behind, that there's no real point in keeping them separate.

Once it's merged, I want to fix the checks that we have and then see if we can make a formal release of the package, which I think is long overdue already.

@wbaccinelli , what's your opinion on this?

**Comment by psomhorst** [comment]
@DaniBodor Agreed. There are a few projects at our end starting up. It would be great for them to base their projects on main. Especially because we want to update some of the branches that branch from main for the new structure. It would be great if we can rebase those on main after the merge, finish them, merge them, and then use that in the new projects.

**Pull request merged**
