### PR TITLE
Add check for event on first frame

### LINKED ISSUE #81: Test Draeger data with `Event` on first frame
There were issues when loading data starting after the first frame if there was a 'PhaseIndicator' or 'Event' on the first loaded frame. I solved this by reading an additional frame before the first frame, but not storing its data in the `Sequence` object.
I wonder what happens with data where the actual first frame has a similar attribute on the very first frame in the data, as there it is not possible to preload a frame.

https://github.com/EIT-ALIVE/eitprocessing/blob/27023526d46a6935911bab76f3c62e981e0b93c0/tests/test_sequence.py#L208-L221

### PR DESCRIPTION
**Pull request by psomhorst**
Closes #81 

I tested this by removing all data before a frame with an event from a BIN file.

### CODE REVIEW

**Review by DaniBodor — APPROVED** [review]

**Comment by DaniBodor** [comment]
Ideally we would add a test for this as well, to avoid someone in the future thinking: "why is this written so complicated" and then trying to clean it up therein breaking it again.
This would require adding another dataset to the environment though...

**Comment by psomhorst** [comment]
> Ideally we would add a test for this as well, to avoid someone in the future thinking: "why is this written so complicated" and then trying to clean it up therein breaking it again. This would require adding another dataset to the environment though...

This makes sense. If I supply it to you through another channel, could you add it to the test build? I'll write a test for it before merging.

**Comment by psomhorst** [comment]
> > > Ideally we would add a test for this as well, to avoid someone in the future thinking: "why is this written so complicated" and then trying to clean it up therein breaking it again. This would require adding another dataset to the environment though...
> > 
> > 
> > This makes sense. If I supply it to you through another channel, could you add it to the test build? I'll write a test for it before merging.
> 
> @wbaccinelli , any chance you could do this, I don't remember by heart how to do it and would need to look up my notes somewhere. Ideally, could you also write a quick how-to in the README.dev.md for this?
 
I was able to add the data to the package myself. 

- Make a personal access token (https://github.com/settings/tokens) with "read:package" and "write:package" rights
- `> docker login ghcr.io -u <username>` - use token as password
- `> docker pull ghcr.io/eit-alive/eittestdata:latest`
- `> docker run -i -t --name eittestdata_container ghcr.io/eit-alive/eittestdata:latest /bin/bash`
- In a separate terminal:
  - `> docker cp <file path> eittestdata_container:/eitprocessing/tests/test_data`
  - `docker commit eittestdata_container ghcr.io/eit-alive/eittestdata:<TAG>`
- In running docker container: `exit`
- `> docker push ghcr.io/eit-alive/eittestdata:<TAG>`

@DaniBodor Is there a way to test whether the tests work with the tag `add-data` before pushing it as latest?

**Comment by wbaccinelli** [comment]
> > > Ideally we would add a test for this as well, to avoid someone in the future thinking: "why is this written so complicated" and then trying to clean it up therein breaking it again. This would require adding another dataset to the environment though...
> > 
> > 
> > This makes sense. If I supply it to you through another channel, could you add it to the test build? I'll write a test for it before merging.
> 
> @wbaccinelli , any chance you could do this, I don't remember by heart how to do it and would need to look up my notes somewhere. Ideally, could you also write a quick how-to in the README.dev.md for this?

I can add a new dataset to the Docker image, just tell me which one. It's a good idea to add the process to the documentation. I would add also the Dockerfile. We probably also need to tag the images in a smart way, to avoid corrupting the test by mistakenly uploading a new faulty image.

**Comment by wbaccinelli** [comment]
> > > > Ideally we would add a test for this as well, to avoid someone in the future thinking: "why is this written so complicated" and then trying to clean it up therein breaking it again. This would require adding another dataset to the environment though...
> > > 
> > > 
> > > This makes sense. If I supply it to you through another channel, could you add it to the test build? I'll write a test for it before merging.
> > 
> > 
> > @wbaccinelli , any chance you could do this, I don't remember by heart how to do it and would need to look up my notes somewhere. Ideally, could you also write a quick how-to in the README.dev.md for this?
> 
> I was able to add the data to the package myself.
> 
> * Make a personal access token (https://github.com/settings/tokens) with "read:package" and "write:package" rights
> * `> docker login ghcr.io -u <username>` - use token as password
> * `> docker pull ghcr.io/eit-alive/eittestdata:latest`
> * `> docker run -i -t --name eittestdata_container ghcr.io/eit-alive/eittestdata:latest /bin/bash`
> * In a separate terminal:
>   
>   * `> docker cp <file path> eittestdata_container:/eitprocessing/tests/test_data`
>   * `> docker commit eittestdata_container ghcr.io/eit-alive/eittestdata:<TAG>`
> * In running docker container: `exit`
> * `> docker push ghcr.io/eit-alive/eittestdata:<TAG>`
> 
> ~@DaniBodor Is there a way to test whether the tests work with the tag `add-data` before pushing it as latest?~
> 
> I pushed it as latest (with the option to remove it and restore the previous image as latest). All tests kept running, including a test using the new file.
> 
> This only changes an existing image. It would be better if we would have the DockerFile that creates it from 0.

I just read this comment. In genera,  it might be easier to just recreate the Docker image using the [Dockerfile](https://github.com/EIT-ALIVE/eitprocessing/blob/main/.helpers/Dockerfile) and then push it with the tag we want.

**Pull request merged**
