### PR TITLE
Add test for building docs

### LINKED ISSUE #254: update documentation building workflow to mkdocs
I wanted to create a workflow that checks whether the documentation can be built without errors. This issue might be a duplicate of #252 though.

blocked by #233

### PR DESCRIPTION
**Pull request by psomhorst**
Closes #254

### CODE REVIEW

**Comment by psomhorst** [comment]
Test documentation build check will fail if documentation can't be built.

https://github.com/EIT-ALIVE/eitprocessing/actions/runs/11437789439/job/31818036113?pr=318

**Review by DaniBodor — CHANGES_REQUESTED** [review]
nice job!

Have you tested whether it indeed fails if there's something off? 

Also, this workflow is ignored if the only change is to md files (see line 11). Could this result in a failed documentation build not being picked up if there are documentation only changes? If so, it may be worthwhile moving it to a separate yml.

**Comment by psomhorst** [comment]
> Have you tested whether it indeed fails if there's something off?

Yes, see the comment above. Commit c382f4f (9c567ea before rebase) was pushed to this PR with an intentional error and reverted with 4605245. The checks for that commit [failed as expected](https://github.com/EIT-ALIVE/eitprocessing/actions/runs/11437789439/job/31818036113?pr=318).

> Also, this workflow is ignored if the only change is to md files (see line 11). Could this result in a failed documentation build not being picked up if there are documentation only changes? If so, it may be worthwhile moving it to a separate yml.

Good catch. I moved it to a separate action.

**Comment by DaniBodor** [comment]
> > Have you tested whether it indeed fails if there's something off?
> 
> Yes, see the comment above. Commit [c382f4f](https://github.com/EIT-ALIVE/eitprocessing/commit/c382f4f1c09f50b931a85d7f4a921d36f76bbf7e) ([9c567ea](https://github.com/EIT-ALIVE/eitprocessing/commit/9c567ea9b3f015fc80161afb35b373d4830a988f) before rebase) was pushed to this PR with an intentional error and reverted with [4605245](https://github.com/EIT-ALIVE/eitprocessing/commit/460524562dc63e3e1795c09cbb18041b4e440f6a). The checks for that commit [failed as expected](https://github.com/EIT-ALIVE/eitprocessing/actions/runs/11437789439/job/31818036113?pr=318).

My bad, I went straight into the code review and forgot to read the comments.

**Review by DaniBodor — APPROVED** [review]

**Pull request merged**
