### PR TITLE
CI: finalize core infrastructure

### LINKED ISSUE #28: implement coveralls

### LINKED ISSUE #55: markdown link check
look whether it is working as intended and either get rid of it or fix broken links

### PR DESCRIPTION
**Pull request by DaniBodor**
adjusted from https://github.com/DeepRank/deeprank-core/blob/main/.github/workflows/coveralls.yml

blocked by #27 (to test if it works as intended)

fixes #55, #32, #28, #71

### CODE REVIEW

**Comment by drcandacemakedamoore** [comment]
Let's wait until issues/27 is closed and put on main, then it can be rebased on the main, and properly tested

**Comment by drcandacemakedamoore** [comment]
@DaniBodor if you pulled my code onto the main, then in theory this branch just needs a rebase on the main, and then it can start running properly.

**Comment by DaniBodor** [comment]
Coveralls cannot currently find the test data on the docker.

**Comment by DaniBodor** [comment]
Thanks, @wbaccinelli.

**Pull request merged**
