### PR TITLE
docs: pip installation instructions

### PR DESCRIPTION
**Pull request by DaniBodor**
- Clarified pip install instructions
- Removed conda env + install instructions for that
- Checked that pytest and notebooks run as expected after pip install

### CODE REVIEW

**Comment by DaniBodor** [comment]
Unlcear why I am getting a conflict from the removed environment.

**Comment by drcandacemakedamoore** [comment]
> Unclear why I am getting a conflict from the removed environment.
> 
> EDIT: I wasn't on newest main after all. I `pull --rebase`d the newest main, and then did a `git rebase main` in my branch and resolved the conflict. I now notice that the `git log --graph` is branching after all. What did I do wrong?

Not 100% sure but it looks like you put at least one merge on your branch ([4b26896](https://github.com/EIT-ALIVE/eitprocessing/pull/30/commits/4b268967641043fe9ba01ed281eb72bfede2fd08)). We have a clean linear history until your branch, and then some doubled commits and merge on yours. For speed, since it's just erasing one file and rewriting a markdown, I would open a new branch off the updated main (make sure to git pull on the main) with these changes, because unwinding all your work with the merge and whatnot may take longer.

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
The changes themselves are fine. Please note that without a conda environment,  and only a pip install, we can by definition basically only work with Python here (which is fine). You will however need to clean your history here as you seem to have merged on the branch, which will of course bring a merge into the main.

**Comment by DaniBodor** [comment]
Recreated with linear history in #31

**Pull request closed without merging**
