### PR TITLE
Integrate eitbinary

### PR DESCRIPTION
**Pull request by DaniBodor**
Copied code and requirements from eitbinary to eitprocessing

### CODE REVIEW

**Comment by drcandacemakedamoore** [comment]
Installation instructions are not good for production environment (only good if you will never build a package). We must use Python 3.10 forward for the code from eitbinary to work ( this may be why the documentation build failed by the way). There is no environment.yml , so your have to hand build the environment by guessing from the cfg file (bad) . Please note that we have setup.py, setup.cfg and pyproject.toml - and all of this could be accomplished in setup.py (your choice). We need to see once we run the .bumpversion if it updates with a  .__version__ (no idea)

**Comment by drcandacemakedamoore** [comment]
Also unclear why we need Sonarcloud (I think we don't) but I believe we would have to set up an account with them.

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
Please see my comments, and probably pull the sonarcloud stuff unless you want it before putting on the main branch

**Comment by DaniBodor** [comment]
> There is no environment.yml , so your have to hand build the environment by guessing from the cfg file (bad) .

Why is this better than just running `pip install -e ./` in a freshly created environment? By pip installing, you also immediately have the current repo installed as well, which I don't think is the case for the environment.
(I realize that the setup instructions for that weren't there yet).

**Comment by drcandacemakedamoore** [comment]
If the notebook doesn't run with the environment created in environment.yml, then the environment.yml should just be changed. In theory conda may be better at making sure all installed packages do not conlict than pip. I think the main thing is to be consistent, even down to the conda channel, as much as possible. I will add some additional notes on why I personally might avoid pip in a bit

**Comment by drcandacemakedamoore** [comment]
Whichever way we go- conda or pip, it will effect many things like the testing, so just decide which, then we may to adjust the testing instruction.

**Pull request merged**
