### PR TITLE
Drcandacemakedamoore/docker

### PR DESCRIPTION
**Pull request by drcandacemakedamoore**
The tests still fail because the data needs to be in image- awaiting permission. Also we need to with  the correct data make two separate images for Python 3.10 and Python 3.11.

### CODE REVIEW

**Comment by DaniBodor** [comment]
shall I wait with reviewing until the data is formatted properly?

**Comment by drcandacemakedamoore** [comment]
Tests are passing on data now @DaniBodor

**Review by DaniBodor — COMMENTED** [review]
I notice that there is now 135MB+ data on this repo. I thought the point of docker containers was that the data doesn't have to be on the repo at all, or did I misunderstand that?

Also, @ajonkman yesterday added another file on Teams of just 7MB. Maybe we can use that one instead to decrease the size.

**Comment by drcandacemakedamoore** [comment]
I think I accidentally pushed up a file then. I'll have to check back on
this.

**Comment by drcandacemakedamoore** [comment]
I pulled the accidentally pushed files from the git history with a rebase/amend. Should be fine now @DaniBodor

**Comment by DaniBodor** [comment]
Is there any way to delete commit 39947fceb23a5b2cf87fa25d9bda18f830ccfd1f, which now adds that unnecessary data to the .git?

**Review by DaniBodor — APPROVED** [review]
Is there any way to delete commit https://github.com/EIT-ALIVE/eitprocessing/commit/39947fceb23a5b2cf87fa25d9bda18f830ccfd1f, which now adds that unnecessary data to the .git?

**Pull request merged**
